spring:
  datasource:
    username: root
    password:
    url: 'jdbc:mysql://localhost:3306/mytest?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai'
server:
  port: 8099
