server:
  port: 8878
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: 'shopping-goods-ms'
  datasource:
    username: root
    password:
    url: 'jdbc:mysql://localhost:3306/pinyougoudb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai'
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
pagehelper:
  helper-dialect: mysql
  reasonable: true