server:
  port: 8827
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: 127.0.0.1:9300
      cluster-name: elasticsearch
  application:
    name: 'shopping-elastisearch-ms'
  datasource:
    url: jdbc:mysql://localhost:3306/pinyougoudb?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: