eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8899
spring:
  application:
    name: shopping-zuul
zuul:
  routes:
    api-goods:
      path: /shopping-goods-ms/**
      service-id: shopping-goods-ms
    api-content:
      path: /shopping-content-ms/**
      service-id: shopping-content-ms
    api-search:
      path: /shopping-search-ms/**
      service-id: shopping-search-ms
    api-page:
      path: /shopping-page-ms/**
      service-id: shopping-page-ms
    api-auth:
      path: /doLogin
      service-id: shopping-auth-center
    api-microservice:
        path: /microservice/**
        service-id: jwt-microservice
    sensitive-headers:
    #api-elastisearch:
    # path: /shopping-elastisearch-ms/**
    # service-id: shopping-elastisearch-ms

ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000

host:
  maxTotalConnections: 10000
  maxPerRouteConnections: 10000
  semaphore:
    max-semaphores: 200
