spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/auctiondb?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  devtools:
    restart:
      enabled: true
pagehelper:
  helper-dialect: mysql
  reasonable: true
file:
  staticAccessPath: '/upload/**'
  uploadFileFolder: 'D:\\file'