server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pinyougoudb?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password:
  data:
    solr:
      host: http://127.0.0.1:8080/solr
